/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class cFileMappingDroneCharTelemetryClient {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected cFileMappingDroneCharTelemetryClient(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(cFileMappingDroneCharTelemetryClient obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        JNIFileMappingDroneCharTelemetryClientJNI.delete_cFileMappingDroneCharTelemetryClient(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public cFileMappingDroneCharTelemetryClient(boolean _DebugFlag) {
    this(JNIFileMappingDroneCharTelemetryClientJNI.new_cFileMappingDroneCharTelemetryClient(_DebugFlag), true);
  }

  public boolean OpenClient(String NameSharedMem) {
    return JNIFileMappingDroneCharTelemetryClientJNI.cFileMappingDroneCharTelemetryClient_OpenClient(swigCPtr, this, NameSharedMem);
  }

  public void CloseClient() {
    JNIFileMappingDroneCharTelemetryClientJNI.cFileMappingDroneCharTelemetryClient_CloseClient(swigCPtr, this);
  }

  public cVirtualDroneCharTelemetry ReadMapFileToVirtualDroneCharTelemetryStruct(cVirtualDroneCharTelemetry Data) {
    long cPtr = JNIFileMappingDroneCharTelemetryClientJNI.cFileMappingDroneCharTelemetryClient_ReadMapFileToVirtualDroneCharTelemetryStruct(swigCPtr, this, cVirtualDroneCharTelemetry.getCPtr(Data), Data);
    return (cPtr == 0) ? null : new cVirtualDroneCharTelemetry(cPtr, false);
  }

  public boolean WriteVirtualDroneCharTelemetryStructToMapFile(cVirtualDroneCharTelemetry Data) {
    return JNIFileMappingDroneCharTelemetryClientJNI.cFileMappingDroneCharTelemetryClient_WriteVirtualDroneCharTelemetryStructToMapFile(swigCPtr, this, cVirtualDroneCharTelemetry.getCPtr(Data), Data);
  }

  public void PrintDebug(String msg, boolean _Return) {
    JNIFileMappingDroneCharTelemetryClientJNI.cFileMappingDroneCharTelemetryClient_PrintDebug(swigCPtr, this, msg, _Return);
  }

  public void PrintStruct(cVirtualDroneCharTelemetry Data) {
    JNIFileMappingDroneCharTelemetryClientJNI.cFileMappingDroneCharTelemetryClient_PrintStruct(swigCPtr, this, cVirtualDroneCharTelemetry.getCPtr(Data), Data);
  }

  public boolean getDebugMode() {
    return JNIFileMappingDroneCharTelemetryClientJNI.cFileMappingDroneCharTelemetryClient_getDebugMode(swigCPtr, this);
  }

  public cVirtualDroneCharTelemetry getVirtualDroneCharTelemetryPtr() {
    long cPtr = JNIFileMappingDroneCharTelemetryClientJNI.cFileMappingDroneCharTelemetryClient_getVirtualDroneCharTelemetryPtr(swigCPtr, this);
    return (cPtr == 0) ? null : new cVirtualDroneCharTelemetry(cPtr, false);
  }

  public boolean getVirtualDroneCharTelemetryMutexBlocAccess() {
    return JNIFileMappingDroneCharTelemetryClientJNI.cFileMappingDroneCharTelemetryClient_getVirtualDroneCharTelemetryMutexBlocAccess(swigCPtr, this);
  }

  public double get_val_0() {
    return JNIFileMappingDroneCharTelemetryClientJNI.cFileMappingDroneCharTelemetryClient_get_val_0(swigCPtr, this);
  }

  public double get_val_1() {
    return JNIFileMappingDroneCharTelemetryClientJNI.cFileMappingDroneCharTelemetryClient_get_val_1(swigCPtr, this);
  }

  public double get_val_2() {
    return JNIFileMappingDroneCharTelemetryClientJNI.cFileMappingDroneCharTelemetryClient_get_val_2(swigCPtr, this);
  }

  public double get_val_3() {
    return JNIFileMappingDroneCharTelemetryClientJNI.cFileMappingDroneCharTelemetryClient_get_val_3(swigCPtr, this);
  }

  public double get_val_4() {
    return JNIFileMappingDroneCharTelemetryClientJNI.cFileMappingDroneCharTelemetryClient_get_val_4(swigCPtr, this);
  }

  public double get_val_5() {
    return JNIFileMappingDroneCharTelemetryClientJNI.cFileMappingDroneCharTelemetryClient_get_val_5(swigCPtr, this);
  }

  public double get_val_6() {
    return JNIFileMappingDroneCharTelemetryClientJNI.cFileMappingDroneCharTelemetryClient_get_val_6(swigCPtr, this);
  }

  public double get_val_7() {
    return JNIFileMappingDroneCharTelemetryClientJNI.cFileMappingDroneCharTelemetryClient_get_val_7(swigCPtr, this);
  }

  public double get_val_8() {
    return JNIFileMappingDroneCharTelemetryClientJNI.cFileMappingDroneCharTelemetryClient_get_val_8(swigCPtr, this);
  }

  public double get_val_9() {
    return JNIFileMappingDroneCharTelemetryClientJNI.cFileMappingDroneCharTelemetryClient_get_val_9(swigCPtr, this);
  }

  public double get_val_10() {
    return JNIFileMappingDroneCharTelemetryClientJNI.cFileMappingDroneCharTelemetryClient_get_val_10(swigCPtr, this);
  }

  public double get_val_11() {
    return JNIFileMappingDroneCharTelemetryClientJNI.cFileMappingDroneCharTelemetryClient_get_val_11(swigCPtr, this);
  }

  public double get_val_12() {
    return JNIFileMappingDroneCharTelemetryClientJNI.cFileMappingDroneCharTelemetryClient_get_val_12(swigCPtr, this);
  }

  public double get_val_13() {
    return JNIFileMappingDroneCharTelemetryClientJNI.cFileMappingDroneCharTelemetryClient_get_val_13(swigCPtr, this);
  }

  public double get_val_14() {
    return JNIFileMappingDroneCharTelemetryClientJNI.cFileMappingDroneCharTelemetryClient_get_val_14(swigCPtr, this);
  }

  public double get_val_15() {
    return JNIFileMappingDroneCharTelemetryClientJNI.cFileMappingDroneCharTelemetryClient_get_val_15(swigCPtr, this);
  }

  public double get_val_16() {
    return JNIFileMappingDroneCharTelemetryClientJNI.cFileMappingDroneCharTelemetryClient_get_val_16(swigCPtr, this);
  }

  public double get_val_17() {
    return JNIFileMappingDroneCharTelemetryClientJNI.cFileMappingDroneCharTelemetryClient_get_val_17(swigCPtr, this);
  }

  public double get_val_18() {
    return JNIFileMappingDroneCharTelemetryClientJNI.cFileMappingDroneCharTelemetryClient_get_val_18(swigCPtr, this);
  }

  public double get_val_19() {
    return JNIFileMappingDroneCharTelemetryClientJNI.cFileMappingDroneCharTelemetryClient_get_val_19(swigCPtr, this);
  }

  public void setDebugMode(boolean _DebugMode) {
    JNIFileMappingDroneCharTelemetryClientJNI.cFileMappingDroneCharTelemetryClient_setDebugMode(swigCPtr, this, _DebugMode);
  }

  public void setVirtualDroneCharTelemetryPtr(cVirtualDroneCharTelemetry VTStruct) {
    JNIFileMappingDroneCharTelemetryClientJNI.cFileMappingDroneCharTelemetryClient_setVirtualDroneCharTelemetryPtr(swigCPtr, this, cVirtualDroneCharTelemetry.getCPtr(VTStruct), VTStruct);
  }

  public void setVirtualDroneCharTelemetryMutexBlocAccess(boolean blocaccess) {
    JNIFileMappingDroneCharTelemetryClientJNI.cFileMappingDroneCharTelemetryClient_setVirtualDroneCharTelemetryMutexBlocAccess(swigCPtr, this, blocaccess);
  }

  public void set_val_0(double _val_0) {
    JNIFileMappingDroneCharTelemetryClientJNI.cFileMappingDroneCharTelemetryClient_set_val_0(swigCPtr, this, _val_0);
  }

  public void set_val_1(double _val_1) {
    JNIFileMappingDroneCharTelemetryClientJNI.cFileMappingDroneCharTelemetryClient_set_val_1(swigCPtr, this, _val_1);
  }

  public void set_val_2(double _val_2) {
    JNIFileMappingDroneCharTelemetryClientJNI.cFileMappingDroneCharTelemetryClient_set_val_2(swigCPtr, this, _val_2);
  }

  public void set_val_3(double _val_3) {
    JNIFileMappingDroneCharTelemetryClientJNI.cFileMappingDroneCharTelemetryClient_set_val_3(swigCPtr, this, _val_3);
  }

  public void set_val_4(double _val_4) {
    JNIFileMappingDroneCharTelemetryClientJNI.cFileMappingDroneCharTelemetryClient_set_val_4(swigCPtr, this, _val_4);
  }

  public void set_val_5(double _val_5) {
    JNIFileMappingDroneCharTelemetryClientJNI.cFileMappingDroneCharTelemetryClient_set_val_5(swigCPtr, this, _val_5);
  }

  public void set_val_6(double _val_6) {
    JNIFileMappingDroneCharTelemetryClientJNI.cFileMappingDroneCharTelemetryClient_set_val_6(swigCPtr, this, _val_6);
  }

  public void set_val_7(double _val_7) {
    JNIFileMappingDroneCharTelemetryClientJNI.cFileMappingDroneCharTelemetryClient_set_val_7(swigCPtr, this, _val_7);
  }

  public void set_val_8(double _val_8) {
    JNIFileMappingDroneCharTelemetryClientJNI.cFileMappingDroneCharTelemetryClient_set_val_8(swigCPtr, this, _val_8);
  }

  public void set_val_9(double _val_9) {
    JNIFileMappingDroneCharTelemetryClientJNI.cFileMappingDroneCharTelemetryClient_set_val_9(swigCPtr, this, _val_9);
  }

  public void set_val_10(double _val_10) {
    JNIFileMappingDroneCharTelemetryClientJNI.cFileMappingDroneCharTelemetryClient_set_val_10(swigCPtr, this, _val_10);
  }

  public void set_val_11(double _val_11) {
    JNIFileMappingDroneCharTelemetryClientJNI.cFileMappingDroneCharTelemetryClient_set_val_11(swigCPtr, this, _val_11);
  }

  public void set_val_12(double _val_12) {
    JNIFileMappingDroneCharTelemetryClientJNI.cFileMappingDroneCharTelemetryClient_set_val_12(swigCPtr, this, _val_12);
  }

  public void set_val_13(double _val_13) {
    JNIFileMappingDroneCharTelemetryClientJNI.cFileMappingDroneCharTelemetryClient_set_val_13(swigCPtr, this, _val_13);
  }

  public void set_val_14(double _val_14) {
    JNIFileMappingDroneCharTelemetryClientJNI.cFileMappingDroneCharTelemetryClient_set_val_14(swigCPtr, this, _val_14);
  }

  public void set_val_15(double _val_15) {
    JNIFileMappingDroneCharTelemetryClientJNI.cFileMappingDroneCharTelemetryClient_set_val_15(swigCPtr, this, _val_15);
  }

  public void set_val_16(double _val_16) {
    JNIFileMappingDroneCharTelemetryClientJNI.cFileMappingDroneCharTelemetryClient_set_val_16(swigCPtr, this, _val_16);
  }

  public void set_val_17(double _val_17) {
    JNIFileMappingDroneCharTelemetryClientJNI.cFileMappingDroneCharTelemetryClient_set_val_17(swigCPtr, this, _val_17);
  }

  public void set_val_18(double _val_18) {
    JNIFileMappingDroneCharTelemetryClientJNI.cFileMappingDroneCharTelemetryClient_set_val_18(swigCPtr, this, _val_18);
  }

  public void set_val_19(double _val_19) {
    JNIFileMappingDroneCharTelemetryClientJNI.cFileMappingDroneCharTelemetryClient_set_val_19(swigCPtr, this, _val_19);
  }

}
