/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class cVirtualDroneCharTelemetry {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected cVirtualDroneCharTelemetry(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(cVirtualDroneCharTelemetry obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        JNIFileMappingDroneCharTelemetryClientJNI.delete_cVirtualDroneCharTelemetry(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setMutexBlocAccess(boolean value) {
    JNIFileMappingDroneCharTelemetryClientJNI.cVirtualDroneCharTelemetry_MutexBlocAccess_set(swigCPtr, this, value);
  }

  public boolean getMutexBlocAccess() {
    return JNIFileMappingDroneCharTelemetryClientJNI.cVirtualDroneCharTelemetry_MutexBlocAccess_get(swigCPtr, this);
  }

  public void setDroneCharTelemetryDataPtr(SWIGTYPE_p_unsigned_char value) {
    JNIFileMappingDroneCharTelemetryClientJNI.cVirtualDroneCharTelemetry_DroneCharTelemetryDataPtr_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getDroneCharTelemetryDataPtr() {
    long cPtr = JNIFileMappingDroneCharTelemetryClientJNI.cVirtualDroneCharTelemetry_DroneCharTelemetryDataPtr_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public void setVal_0(float value) {
    JNIFileMappingDroneCharTelemetryClientJNI.cVirtualDroneCharTelemetry_val_0_set(swigCPtr, this, value);
  }

  public float getVal_0() {
    return JNIFileMappingDroneCharTelemetryClientJNI.cVirtualDroneCharTelemetry_val_0_get(swigCPtr, this);
  }

  public void setVal_1(float value) {
    JNIFileMappingDroneCharTelemetryClientJNI.cVirtualDroneCharTelemetry_val_1_set(swigCPtr, this, value);
  }

  public float getVal_1() {
    return JNIFileMappingDroneCharTelemetryClientJNI.cVirtualDroneCharTelemetry_val_1_get(swigCPtr, this);
  }

  public void setVal_2(float value) {
    JNIFileMappingDroneCharTelemetryClientJNI.cVirtualDroneCharTelemetry_val_2_set(swigCPtr, this, value);
  }

  public float getVal_2() {
    return JNIFileMappingDroneCharTelemetryClientJNI.cVirtualDroneCharTelemetry_val_2_get(swigCPtr, this);
  }

  public void setVal_3(float value) {
    JNIFileMappingDroneCharTelemetryClientJNI.cVirtualDroneCharTelemetry_val_3_set(swigCPtr, this, value);
  }

  public float getVal_3() {
    return JNIFileMappingDroneCharTelemetryClientJNI.cVirtualDroneCharTelemetry_val_3_get(swigCPtr, this);
  }

  public void setVal_4(float value) {
    JNIFileMappingDroneCharTelemetryClientJNI.cVirtualDroneCharTelemetry_val_4_set(swigCPtr, this, value);
  }

  public float getVal_4() {
    return JNIFileMappingDroneCharTelemetryClientJNI.cVirtualDroneCharTelemetry_val_4_get(swigCPtr, this);
  }

  public void setVal_5(float value) {
    JNIFileMappingDroneCharTelemetryClientJNI.cVirtualDroneCharTelemetry_val_5_set(swigCPtr, this, value);
  }

  public float getVal_5() {
    return JNIFileMappingDroneCharTelemetryClientJNI.cVirtualDroneCharTelemetry_val_5_get(swigCPtr, this);
  }

  public void setVal_6(float value) {
    JNIFileMappingDroneCharTelemetryClientJNI.cVirtualDroneCharTelemetry_val_6_set(swigCPtr, this, value);
  }

  public float getVal_6() {
    return JNIFileMappingDroneCharTelemetryClientJNI.cVirtualDroneCharTelemetry_val_6_get(swigCPtr, this);
  }

  public void setVal_7(float value) {
    JNIFileMappingDroneCharTelemetryClientJNI.cVirtualDroneCharTelemetry_val_7_set(swigCPtr, this, value);
  }

  public float getVal_7() {
    return JNIFileMappingDroneCharTelemetryClientJNI.cVirtualDroneCharTelemetry_val_7_get(swigCPtr, this);
  }

  public void setVal_8(float value) {
    JNIFileMappingDroneCharTelemetryClientJNI.cVirtualDroneCharTelemetry_val_8_set(swigCPtr, this, value);
  }

  public float getVal_8() {
    return JNIFileMappingDroneCharTelemetryClientJNI.cVirtualDroneCharTelemetry_val_8_get(swigCPtr, this);
  }

  public void setVal_9(float value) {
    JNIFileMappingDroneCharTelemetryClientJNI.cVirtualDroneCharTelemetry_val_9_set(swigCPtr, this, value);
  }

  public float getVal_9() {
    return JNIFileMappingDroneCharTelemetryClientJNI.cVirtualDroneCharTelemetry_val_9_get(swigCPtr, this);
  }

  public void setVal_10(float value) {
    JNIFileMappingDroneCharTelemetryClientJNI.cVirtualDroneCharTelemetry_val_10_set(swigCPtr, this, value);
  }

  public float getVal_10() {
    return JNIFileMappingDroneCharTelemetryClientJNI.cVirtualDroneCharTelemetry_val_10_get(swigCPtr, this);
  }

  public void setVal_11(float value) {
    JNIFileMappingDroneCharTelemetryClientJNI.cVirtualDroneCharTelemetry_val_11_set(swigCPtr, this, value);
  }

  public float getVal_11() {
    return JNIFileMappingDroneCharTelemetryClientJNI.cVirtualDroneCharTelemetry_val_11_get(swigCPtr, this);
  }

  public void setVal_12(float value) {
    JNIFileMappingDroneCharTelemetryClientJNI.cVirtualDroneCharTelemetry_val_12_set(swigCPtr, this, value);
  }

  public float getVal_12() {
    return JNIFileMappingDroneCharTelemetryClientJNI.cVirtualDroneCharTelemetry_val_12_get(swigCPtr, this);
  }

  public void setVal_13(float value) {
    JNIFileMappingDroneCharTelemetryClientJNI.cVirtualDroneCharTelemetry_val_13_set(swigCPtr, this, value);
  }

  public float getVal_13() {
    return JNIFileMappingDroneCharTelemetryClientJNI.cVirtualDroneCharTelemetry_val_13_get(swigCPtr, this);
  }

  public void setVal_14(float value) {
    JNIFileMappingDroneCharTelemetryClientJNI.cVirtualDroneCharTelemetry_val_14_set(swigCPtr, this, value);
  }

  public float getVal_14() {
    return JNIFileMappingDroneCharTelemetryClientJNI.cVirtualDroneCharTelemetry_val_14_get(swigCPtr, this);
  }

  public void setVal_15(float value) {
    JNIFileMappingDroneCharTelemetryClientJNI.cVirtualDroneCharTelemetry_val_15_set(swigCPtr, this, value);
  }

  public float getVal_15() {
    return JNIFileMappingDroneCharTelemetryClientJNI.cVirtualDroneCharTelemetry_val_15_get(swigCPtr, this);
  }

  public void setVal_16(float value) {
    JNIFileMappingDroneCharTelemetryClientJNI.cVirtualDroneCharTelemetry_val_16_set(swigCPtr, this, value);
  }

  public float getVal_16() {
    return JNIFileMappingDroneCharTelemetryClientJNI.cVirtualDroneCharTelemetry_val_16_get(swigCPtr, this);
  }

  public void setVal_17(float value) {
    JNIFileMappingDroneCharTelemetryClientJNI.cVirtualDroneCharTelemetry_val_17_set(swigCPtr, this, value);
  }

  public float getVal_17() {
    return JNIFileMappingDroneCharTelemetryClientJNI.cVirtualDroneCharTelemetry_val_17_get(swigCPtr, this);
  }

  public void setVal_18(float value) {
    JNIFileMappingDroneCharTelemetryClientJNI.cVirtualDroneCharTelemetry_val_18_set(swigCPtr, this, value);
  }

  public float getVal_18() {
    return JNIFileMappingDroneCharTelemetryClientJNI.cVirtualDroneCharTelemetry_val_18_get(swigCPtr, this);
  }

  public void setVal_19(float value) {
    JNIFileMappingDroneCharTelemetryClientJNI.cVirtualDroneCharTelemetry_val_19_set(swigCPtr, this, value);
  }

  public float getVal_19() {
    return JNIFileMappingDroneCharTelemetryClientJNI.cVirtualDroneCharTelemetry_val_19_get(swigCPtr, this);
  }

  public cVirtualDroneCharTelemetry() {
    this(JNIFileMappingDroneCharTelemetryClientJNI.new_cVirtualDroneCharTelemetry(), true);
  }

}
