# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.1.1
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _pyFileMappingDroneCharTelemetryClient
else:
    import _pyFileMappingDroneCharTelemetryClient

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class cVirtualDroneCharTelemetry(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    MutexBlocAccess = property(_pyFileMappingDroneCharTelemetryClient.cVirtualDroneCharTelemetry_MutexBlocAccess_get, _pyFileMappingDroneCharTelemetryClient.cVirtualDroneCharTelemetry_MutexBlocAccess_set)
    BatteryValue = property(_pyFileMappingDroneCharTelemetryClient.cVirtualDroneCharTelemetry_BatteryValue_get, _pyFileMappingDroneCharTelemetryClient.cVirtualDroneCharTelemetry_BatteryValue_set)
    DriveTime = property(_pyFileMappingDroneCharTelemetryClient.cVirtualDroneCharTelemetry_DriveTime_get, _pyFileMappingDroneCharTelemetryClient.cVirtualDroneCharTelemetry_DriveTime_set)
    TempC = property(_pyFileMappingDroneCharTelemetryClient.cVirtualDroneCharTelemetry_TempC_get, _pyFileMappingDroneCharTelemetryClient.cVirtualDroneCharTelemetry_TempC_set)
    TempF = property(_pyFileMappingDroneCharTelemetryClient.cVirtualDroneCharTelemetry_TempF_get, _pyFileMappingDroneCharTelemetryClient.cVirtualDroneCharTelemetry_TempF_set)
    Altitude = property(_pyFileMappingDroneCharTelemetryClient.cVirtualDroneCharTelemetry_Altitude_get, _pyFileMappingDroneCharTelemetryClient.cVirtualDroneCharTelemetry_Altitude_set)
    Ax = property(_pyFileMappingDroneCharTelemetryClient.cVirtualDroneCharTelemetry_Ax_get, _pyFileMappingDroneCharTelemetryClient.cVirtualDroneCharTelemetry_Ax_set)
    Ay = property(_pyFileMappingDroneCharTelemetryClient.cVirtualDroneCharTelemetry_Ay_get, _pyFileMappingDroneCharTelemetryClient.cVirtualDroneCharTelemetry_Ay_set)
    Az = property(_pyFileMappingDroneCharTelemetryClient.cVirtualDroneCharTelemetry_Az_get, _pyFileMappingDroneCharTelemetryClient.cVirtualDroneCharTelemetry_Az_set)
    FrontDistance = property(_pyFileMappingDroneCharTelemetryClient.cVirtualDroneCharTelemetry_FrontDistance_get, _pyFileMappingDroneCharTelemetryClient.cVirtualDroneCharTelemetry_FrontDistance_set)
    BackDistance = property(_pyFileMappingDroneCharTelemetryClient.cVirtualDroneCharTelemetry_BackDistance_get, _pyFileMappingDroneCharTelemetryClient.cVirtualDroneCharTelemetry_BackDistance_set)
    Pressure = property(_pyFileMappingDroneCharTelemetryClient.cVirtualDroneCharTelemetry_Pressure_get, _pyFileMappingDroneCharTelemetryClient.cVirtualDroneCharTelemetry_Pressure_set)
    DroneCharTelemetryDataPtr = property(_pyFileMappingDroneCharTelemetryClient.cVirtualDroneCharTelemetry_DroneCharTelemetryDataPtr_get, _pyFileMappingDroneCharTelemetryClient.cVirtualDroneCharTelemetry_DroneCharTelemetryDataPtr_set)

    def __init__(self):
        _pyFileMappingDroneCharTelemetryClient.cVirtualDroneCharTelemetry_swiginit(self, _pyFileMappingDroneCharTelemetryClient.new_cVirtualDroneCharTelemetry())
    __swig_destroy__ = _pyFileMappingDroneCharTelemetryClient.delete_cVirtualDroneCharTelemetry

# Register cVirtualDroneCharTelemetry in _pyFileMappingDroneCharTelemetryClient:
_pyFileMappingDroneCharTelemetryClient.cVirtualDroneCharTelemetry_swigregister(cVirtualDroneCharTelemetry)
class cFileMappingDroneCharTelemetryClient(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, _DebugFlag):
        _pyFileMappingDroneCharTelemetryClient.cFileMappingDroneCharTelemetryClient_swiginit(self, _pyFileMappingDroneCharTelemetryClient.new_cFileMappingDroneCharTelemetryClient(_DebugFlag))
    __swig_destroy__ = _pyFileMappingDroneCharTelemetryClient.delete_cFileMappingDroneCharTelemetryClient

    def OpenClient(self, NameSharedMem):
        return _pyFileMappingDroneCharTelemetryClient.cFileMappingDroneCharTelemetryClient_OpenClient(self, NameSharedMem)

    def CloseClient(self):
        return _pyFileMappingDroneCharTelemetryClient.cFileMappingDroneCharTelemetryClient_CloseClient(self)

    def ReadMapFileToVirtualDroneCharTelemetryStruct(self, Data):
        return _pyFileMappingDroneCharTelemetryClient.cFileMappingDroneCharTelemetryClient_ReadMapFileToVirtualDroneCharTelemetryStruct(self, Data)

    def WriteVirtualDroneCharTelemetryStructToMapFile(self, Data):
        return _pyFileMappingDroneCharTelemetryClient.cFileMappingDroneCharTelemetryClient_WriteVirtualDroneCharTelemetryStructToMapFile(self, Data)

    def PrintDebug(self, msg, _Return):
        return _pyFileMappingDroneCharTelemetryClient.cFileMappingDroneCharTelemetryClient_PrintDebug(self, msg, _Return)

    def PrintStruct(self, Data):
        return _pyFileMappingDroneCharTelemetryClient.cFileMappingDroneCharTelemetryClient_PrintStruct(self, Data)

    def getVirtualDroneCharTelemetryPtr(self):
        return _pyFileMappingDroneCharTelemetryClient.cFileMappingDroneCharTelemetryClient_getVirtualDroneCharTelemetryPtr(self)

    def getDebugMode(self):
        return _pyFileMappingDroneCharTelemetryClient.cFileMappingDroneCharTelemetryClient_getDebugMode(self)

    def getVirtualDroneCharTelemetryBatteryValue(self):
        return _pyFileMappingDroneCharTelemetryClient.cFileMappingDroneCharTelemetryClient_getVirtualDroneCharTelemetryBatteryValue(self)

    def getVirtualDroneCharTelemetryDriveTime(self):
        return _pyFileMappingDroneCharTelemetryClient.cFileMappingDroneCharTelemetryClient_getVirtualDroneCharTelemetryDriveTime(self)

    def getVirtualDroneCharTelemetryTempC(self):
        return _pyFileMappingDroneCharTelemetryClient.cFileMappingDroneCharTelemetryClient_getVirtualDroneCharTelemetryTempC(self)

    def getVirtualDroneCharTelemetryTempF(self):
        return _pyFileMappingDroneCharTelemetryClient.cFileMappingDroneCharTelemetryClient_getVirtualDroneCharTelemetryTempF(self)

    def getVirtualDroneCharTelemetryAltitude(self):
        return _pyFileMappingDroneCharTelemetryClient.cFileMappingDroneCharTelemetryClient_getVirtualDroneCharTelemetryAltitude(self)

    def getVirtualDroneCharTelemetryAx(self):
        return _pyFileMappingDroneCharTelemetryClient.cFileMappingDroneCharTelemetryClient_getVirtualDroneCharTelemetryAx(self)

    def getVirtualDroneCharTelemetryAy(self):
        return _pyFileMappingDroneCharTelemetryClient.cFileMappingDroneCharTelemetryClient_getVirtualDroneCharTelemetryAy(self)

    def getVirtualDroneCharTelemetryAz(self):
        return _pyFileMappingDroneCharTelemetryClient.cFileMappingDroneCharTelemetryClient_getVirtualDroneCharTelemetryAz(self)

    def getVirtualDroneCharTelemetryFrontDistance(self):
        return _pyFileMappingDroneCharTelemetryClient.cFileMappingDroneCharTelemetryClient_getVirtualDroneCharTelemetryFrontDistance(self)

    def getVirtualDroneCharTelemetryBackDistance(self):
        return _pyFileMappingDroneCharTelemetryClient.cFileMappingDroneCharTelemetryClient_getVirtualDroneCharTelemetryBackDistance(self)

    def getVirtualDroneCharTelemetryPressure(self):
        return _pyFileMappingDroneCharTelemetryClient.cFileMappingDroneCharTelemetryClient_getVirtualDroneCharTelemetryPressure(self)

    def getVirtualDroneCharTelemetryMutexBlocAccess(self):
        return _pyFileMappingDroneCharTelemetryClient.cFileMappingDroneCharTelemetryClient_getVirtualDroneCharTelemetryMutexBlocAccess(self)

    def setVirtualDroneCharTelemetryPtr(self, VTStruct):
        return _pyFileMappingDroneCharTelemetryClient.cFileMappingDroneCharTelemetryClient_setVirtualDroneCharTelemetryPtr(self, VTStruct)

    def setDebugMode(self, _DebugMode):
        return _pyFileMappingDroneCharTelemetryClient.cFileMappingDroneCharTelemetryClient_setDebugMode(self, _DebugMode)

    def setVirtualDroneCharTelemetryBatteryValue(self, value):
        return _pyFileMappingDroneCharTelemetryClient.cFileMappingDroneCharTelemetryClient_setVirtualDroneCharTelemetryBatteryValue(self, value)

    def setVirtualDroneCharTelemetryDriveTime(self, DriveTime):
        return _pyFileMappingDroneCharTelemetryClient.cFileMappingDroneCharTelemetryClient_setVirtualDroneCharTelemetryDriveTime(self, DriveTime)

    def setVirtualDroneCharTelemetryTempC(self, TempC):
        return _pyFileMappingDroneCharTelemetryClient.cFileMappingDroneCharTelemetryClient_setVirtualDroneCharTelemetryTempC(self, TempC)

    def setVirtualDroneCharTelemetryTempF(self, TempF):
        return _pyFileMappingDroneCharTelemetryClient.cFileMappingDroneCharTelemetryClient_setVirtualDroneCharTelemetryTempF(self, TempF)

    def setVirtualDroneCharTelemetryAltitude(self, Altitude):
        return _pyFileMappingDroneCharTelemetryClient.cFileMappingDroneCharTelemetryClient_setVirtualDroneCharTelemetryAltitude(self, Altitude)

    def setVirtualDroneCharTelemetryAx(self, Ax):
        return _pyFileMappingDroneCharTelemetryClient.cFileMappingDroneCharTelemetryClient_setVirtualDroneCharTelemetryAx(self, Ax)

    def setVirtualDroneCharTelemetryAy(self, Ay):
        return _pyFileMappingDroneCharTelemetryClient.cFileMappingDroneCharTelemetryClient_setVirtualDroneCharTelemetryAy(self, Ay)

    def setVirtualDroneCharTelemetryAz(self, Az):
        return _pyFileMappingDroneCharTelemetryClient.cFileMappingDroneCharTelemetryClient_setVirtualDroneCharTelemetryAz(self, Az)

    def setVirtualDroneCharTelemetryFrontDistance(self, FrontDistance):
        return _pyFileMappingDroneCharTelemetryClient.cFileMappingDroneCharTelemetryClient_setVirtualDroneCharTelemetryFrontDistance(self, FrontDistance)

    def setVirtualDroneCharTelemetryBackDistance(self, BackDistance):
        return _pyFileMappingDroneCharTelemetryClient.cFileMappingDroneCharTelemetryClient_setVirtualDroneCharTelemetryBackDistance(self, BackDistance)

    def setVirtualDroneCharTelemetryPressure(self, Pressure):
        return _pyFileMappingDroneCharTelemetryClient.cFileMappingDroneCharTelemetryClient_setVirtualDroneCharTelemetryPressure(self, Pressure)

    def setVirtualDroneCharTelemetryMutexBlocAccess(self, blocaccess):
        return _pyFileMappingDroneCharTelemetryClient.cFileMappingDroneCharTelemetryClient_setVirtualDroneCharTelemetryMutexBlocAccess(self, blocaccess)

# Register cFileMappingDroneCharTelemetryClient in _pyFileMappingDroneCharTelemetryClient:
_pyFileMappingDroneCharTelemetryClient.cFileMappingDroneCharTelemetryClient_swigregister(cFileMappingDroneCharTelemetryClient)

