@startuml client_sequence
participant "Client" as C
participant "FenetreTraitement" as GUI
participant "thread_reception_\nimage/string" as Threads
participant "UDP\nService" as UDP

== Initialisation ==
C -> GUI: new FenetreTraitement("client")
C -> Threads: reception/cmd.start()

== Boucle Principale ==
loop mainLoop()
    Threads -> C: reception.getImageRecu()
    
    alt Si Image Reçue
        C -> GUI: fenetreClient.setImage(image)
    end
    
    alt Si Interface Modifiée
        GUI -> C: getTraitement()
        C -> UDP: sendTextUDP("C#cmd?...")
    end
end

== Arrêt ==
C -> UDP: sendTextUDP("C#remove...")
C -> Threads: Stop Threads
@enduml