@startuml drone_sequence
participant "Drone" as Drone
participant "VideoCapture" as Camera
participant "thread_reception_string" as CmdThread 
participant "UDP\nService" as UDP

== Initialisation ==
Drone -> Camera: capture.open(0, CAP_V4L2)
Drone -> CmdThread: commande.start()

== Boucle Principale ==
loop mainLoop()
    Drone -> Camera: capture.read(frame)
    
    alt Si Traitement Connecté
        Drone -> UDP: sendImageUDP(frame)
        Drone -> UDP: sendTelemetryUDP("dist;speed;...")
    end
end

== Arrêt ==
Drone -> Camera: capture.release()
Drone -> CmdThread: commande.stop()
@enduml