/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class JNIFileMappingDroneCharTelemetryServeurJNI {
  public final static native void cVirtualDroneCharTelemetry_MutexBlocAccess_set(long jarg1, cVirtualDroneCharTelemetry jarg1_, boolean jarg2);
  public final static native boolean cVirtualDroneCharTelemetry_MutexBlocAccess_get(long jarg1, cVirtualDroneCharTelemetry jarg1_);
  public final static native void cVirtualDroneCharTelemetry_BatteryValue_set(long jarg1, cVirtualDroneCharTelemetry jarg1_, int jarg2);
  public final static native int cVirtualDroneCharTelemetry_BatteryValue_get(long jarg1, cVirtualDroneCharTelemetry jarg1_);
  public final static native void cVirtualDroneCharTelemetry_DriveTime_set(long jarg1, cVirtualDroneCharTelemetry jarg1_, String jarg2);
  public final static native String cVirtualDroneCharTelemetry_DriveTime_get(long jarg1, cVirtualDroneCharTelemetry jarg1_);
  public final static native void cVirtualDroneCharTelemetry_TempC_set(long jarg1, cVirtualDroneCharTelemetry jarg1_, String jarg2);
  public final static native String cVirtualDroneCharTelemetry_TempC_get(long jarg1, cVirtualDroneCharTelemetry jarg1_);
  public final static native void cVirtualDroneCharTelemetry_TempF_set(long jarg1, cVirtualDroneCharTelemetry jarg1_, String jarg2);
  public final static native String cVirtualDroneCharTelemetry_TempF_get(long jarg1, cVirtualDroneCharTelemetry jarg1_);
  public final static native void cVirtualDroneCharTelemetry_Altitude_set(long jarg1, cVirtualDroneCharTelemetry jarg1_, String jarg2);
  public final static native String cVirtualDroneCharTelemetry_Altitude_get(long jarg1, cVirtualDroneCharTelemetry jarg1_);
  public final static native void cVirtualDroneCharTelemetry_Ax_set(long jarg1, cVirtualDroneCharTelemetry jarg1_, double jarg2);
  public final static native double cVirtualDroneCharTelemetry_Ax_get(long jarg1, cVirtualDroneCharTelemetry jarg1_);
  public final static native void cVirtualDroneCharTelemetry_Ay_set(long jarg1, cVirtualDroneCharTelemetry jarg1_, double jarg2);
  public final static native double cVirtualDroneCharTelemetry_Ay_get(long jarg1, cVirtualDroneCharTelemetry jarg1_);
  public final static native void cVirtualDroneCharTelemetry_Az_set(long jarg1, cVirtualDroneCharTelemetry jarg1_, double jarg2);
  public final static native double cVirtualDroneCharTelemetry_Az_get(long jarg1, cVirtualDroneCharTelemetry jarg1_);
  public final static native void cVirtualDroneCharTelemetry_FrontDistance_set(long jarg1, cVirtualDroneCharTelemetry jarg1_, double jarg2);
  public final static native double cVirtualDroneCharTelemetry_FrontDistance_get(long jarg1, cVirtualDroneCharTelemetry jarg1_);
  public final static native void cVirtualDroneCharTelemetry_BackDistance_set(long jarg1, cVirtualDroneCharTelemetry jarg1_, double jarg2);
  public final static native double cVirtualDroneCharTelemetry_BackDistance_get(long jarg1, cVirtualDroneCharTelemetry jarg1_);
  public final static native void cVirtualDroneCharTelemetry_Pressure_set(long jarg1, cVirtualDroneCharTelemetry jarg1_, double jarg2);
  public final static native double cVirtualDroneCharTelemetry_Pressure_get(long jarg1, cVirtualDroneCharTelemetry jarg1_);
  public final static native void cVirtualDroneCharTelemetry_DroneCharTelemetryDataPtr_set(long jarg1, cVirtualDroneCharTelemetry jarg1_, long jarg2);
  public final static native long cVirtualDroneCharTelemetry_DroneCharTelemetryDataPtr_get(long jarg1, cVirtualDroneCharTelemetry jarg1_);
  public final static native long new_cVirtualDroneCharTelemetry();
  public final static native void delete_cVirtualDroneCharTelemetry(long jarg1);
  public final static native long new_cFileMappingDroneCharTelemetryServeur(boolean jarg1);
  public final static native void delete_cFileMappingDroneCharTelemetryServeur(long jarg1);
  public final static native boolean cFileMappingDroneCharTelemetryServeur_OpenServer(long jarg1, cFileMappingDroneCharTelemetryServeur jarg1_, String jarg2);
  public final static native void cFileMappingDroneCharTelemetryServeur_CloseServer(long jarg1, cFileMappingDroneCharTelemetryServeur jarg1_);
  public final static native long cFileMappingDroneCharTelemetryServeur_ReadMapFileToVirtualDroneCharTelemetryStruct(long jarg1, cFileMappingDroneCharTelemetryServeur jarg1_, long jarg2, cVirtualDroneCharTelemetry jarg2_);
  public final static native boolean cFileMappingDroneCharTelemetryServeur_WriteVirtualDroneCharTelemetryStructToMapFile(long jarg1, cFileMappingDroneCharTelemetryServeur jarg1_, long jarg2, cVirtualDroneCharTelemetry jarg2_);
  public final static native void cFileMappingDroneCharTelemetryServeur_PrintDebug(long jarg1, cFileMappingDroneCharTelemetryServeur jarg1_, String jarg2, boolean jarg3);
  public final static native void cFileMappingDroneCharTelemetryServeur_PrintStruct(long jarg1, cFileMappingDroneCharTelemetryServeur jarg1_, long jarg2, cVirtualDroneCharTelemetry jarg2_);
  public final static native long cFileMappingDroneCharTelemetryServeur_getVirtualDroneCharTelemetryPtr(long jarg1, cFileMappingDroneCharTelemetryServeur jarg1_);
  public final static native boolean cFileMappingDroneCharTelemetryServeur_getDebugMode(long jarg1, cFileMappingDroneCharTelemetryServeur jarg1_);
  public final static native int cFileMappingDroneCharTelemetryServeur_getVirtualDroneCharTelemetryBatteryValue(long jarg1, cFileMappingDroneCharTelemetryServeur jarg1_);
  public final static native String cFileMappingDroneCharTelemetryServeur_getVirtualDroneCharTelemetryDriveTime(long jarg1, cFileMappingDroneCharTelemetryServeur jarg1_);
  public final static native String cFileMappingDroneCharTelemetryServeur_getVirtualDroneCharTelemetryTempC(long jarg1, cFileMappingDroneCharTelemetryServeur jarg1_);
  public final static native String cFileMappingDroneCharTelemetryServeur_getVirtualDroneCharTelemetryTempF(long jarg1, cFileMappingDroneCharTelemetryServeur jarg1_);
  public final static native String cFileMappingDroneCharTelemetryServeur_getVirtualDroneCharTelemetryAltitude(long jarg1, cFileMappingDroneCharTelemetryServeur jarg1_);
  public final static native double cFileMappingDroneCharTelemetryServeur_getVirtualDroneCharTelemetryAx(long jarg1, cFileMappingDroneCharTelemetryServeur jarg1_);
  public final static native double cFileMappingDroneCharTelemetryServeur_getVirtualDroneCharTelemetryAy(long jarg1, cFileMappingDroneCharTelemetryServeur jarg1_);
  public final static native double cFileMappingDroneCharTelemetryServeur_getVirtualDroneCharTelemetryAz(long jarg1, cFileMappingDroneCharTelemetryServeur jarg1_);
  public final static native double cFileMappingDroneCharTelemetryServeur_getVirtualDroneCharTelemetryFrontDistance(long jarg1, cFileMappingDroneCharTelemetryServeur jarg1_);
  public final static native double cFileMappingDroneCharTelemetryServeur_getVirtualDroneCharTelemetryBackDistance(long jarg1, cFileMappingDroneCharTelemetryServeur jarg1_);
  public final static native double cFileMappingDroneCharTelemetryServeur_getVirtualDroneCharTelemetryPressure(long jarg1, cFileMappingDroneCharTelemetryServeur jarg1_);
  public final static native boolean cFileMappingDroneCharTelemetryServeur_getVirtualDroneCharTelemetryMutexBlocAccess(long jarg1, cFileMappingDroneCharTelemetryServeur jarg1_);
  public final static native void cFileMappingDroneCharTelemetryServeur_setVirtualDroneCharTelemetryPtr(long jarg1, cFileMappingDroneCharTelemetryServeur jarg1_, long jarg2, cVirtualDroneCharTelemetry jarg2_);
  public final static native void cFileMappingDroneCharTelemetryServeur_setDebugMode(long jarg1, cFileMappingDroneCharTelemetryServeur jarg1_, boolean jarg2);
  public final static native void cFileMappingDroneCharTelemetryServeur_setVirtualDroneCharTelemetryBatteryValue(long jarg1, cFileMappingDroneCharTelemetryServeur jarg1_, int jarg2);
  public final static native void cFileMappingDroneCharTelemetryServeur_setVirtualDroneCharTelemetryDriveTime(long jarg1, cFileMappingDroneCharTelemetryServeur jarg1_, String jarg2);
  public final static native void cFileMappingDroneCharTelemetryServeur_setVirtualDroneCharTelemetryTempC(long jarg1, cFileMappingDroneCharTelemetryServeur jarg1_, String jarg2);
  public final static native void cFileMappingDroneCharTelemetryServeur_setVirtualDroneCharTelemetryTempF(long jarg1, cFileMappingDroneCharTelemetryServeur jarg1_, String jarg2);
  public final static native void cFileMappingDroneCharTelemetryServeur_setVirtualDroneCharTelemetryAltitude(long jarg1, cFileMappingDroneCharTelemetryServeur jarg1_, String jarg2);
  public final static native void cFileMappingDroneCharTelemetryServeur_setVirtualDroneCharTelemetryAx(long jarg1, cFileMappingDroneCharTelemetryServeur jarg1_, double jarg2);
  public final static native void cFileMappingDroneCharTelemetryServeur_setVirtualDroneCharTelemetryAy(long jarg1, cFileMappingDroneCharTelemetryServeur jarg1_, double jarg2);
  public final static native void cFileMappingDroneCharTelemetryServeur_setVirtualDroneCharTelemetryAz(long jarg1, cFileMappingDroneCharTelemetryServeur jarg1_, double jarg2);
  public final static native void cFileMappingDroneCharTelemetryServeur_setVirtualDroneCharTelemetryFrontDistance(long jarg1, cFileMappingDroneCharTelemetryServeur jarg1_, double jarg2);
  public final static native void cFileMappingDroneCharTelemetryServeur_setVirtualDroneCharTelemetryBackDistance(long jarg1, cFileMappingDroneCharTelemetryServeur jarg1_, double jarg2);
  public final static native void cFileMappingDroneCharTelemetryServeur_setVirtualDroneCharTelemetryPressure(long jarg1, cFileMappingDroneCharTelemetryServeur jarg1_, double jarg2);
  public final static native void cFileMappingDroneCharTelemetryServeur_setVirtualDroneCharTelemetryMutexBlocAccess(long jarg1, cFileMappingDroneCharTelemetryServeur jarg1_, boolean jarg2);
}
