/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class cVirtualDroneCharTelemetry {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected cVirtualDroneCharTelemetry(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(cVirtualDroneCharTelemetry obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(cVirtualDroneCharTelemetry obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        JNIFileMappingDroneCharTelemetryClientJNI.delete_cVirtualDroneCharTelemetry(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setMutexBlocAccess(boolean value) {
    JNIFileMappingDroneCharTelemetryClientJNI.cVirtualDroneCharTelemetry_MutexBlocAccess_set(swigCPtr, this, value);
  }

  public boolean getMutexBlocAccess() {
    return JNIFileMappingDroneCharTelemetryClientJNI.cVirtualDroneCharTelemetry_MutexBlocAccess_get(swigCPtr, this);
  }

  public void setBatteryValue(int value) {
    JNIFileMappingDroneCharTelemetryClientJNI.cVirtualDroneCharTelemetry_BatteryValue_set(swigCPtr, this, value);
  }

  public int getBatteryValue() {
    return JNIFileMappingDroneCharTelemetryClientJNI.cVirtualDroneCharTelemetry_BatteryValue_get(swigCPtr, this);
  }

  public void setDriveTime(String value) {
    JNIFileMappingDroneCharTelemetryClientJNI.cVirtualDroneCharTelemetry_DriveTime_set(swigCPtr, this, value);
  }

  public String getDriveTime() {
    return JNIFileMappingDroneCharTelemetryClientJNI.cVirtualDroneCharTelemetry_DriveTime_get(swigCPtr, this);
  }

  public void setTempC(String value) {
    JNIFileMappingDroneCharTelemetryClientJNI.cVirtualDroneCharTelemetry_TempC_set(swigCPtr, this, value);
  }

  public String getTempC() {
    return JNIFileMappingDroneCharTelemetryClientJNI.cVirtualDroneCharTelemetry_TempC_get(swigCPtr, this);
  }

  public void setTempF(String value) {
    JNIFileMappingDroneCharTelemetryClientJNI.cVirtualDroneCharTelemetry_TempF_set(swigCPtr, this, value);
  }

  public String getTempF() {
    return JNIFileMappingDroneCharTelemetryClientJNI.cVirtualDroneCharTelemetry_TempF_get(swigCPtr, this);
  }

  public void setAltitude(String value) {
    JNIFileMappingDroneCharTelemetryClientJNI.cVirtualDroneCharTelemetry_Altitude_set(swigCPtr, this, value);
  }

  public String getAltitude() {
    return JNIFileMappingDroneCharTelemetryClientJNI.cVirtualDroneCharTelemetry_Altitude_get(swigCPtr, this);
  }

  public void setAx(double value) {
    JNIFileMappingDroneCharTelemetryClientJNI.cVirtualDroneCharTelemetry_Ax_set(swigCPtr, this, value);
  }

  public double getAx() {
    return JNIFileMappingDroneCharTelemetryClientJNI.cVirtualDroneCharTelemetry_Ax_get(swigCPtr, this);
  }

  public void setAy(double value) {
    JNIFileMappingDroneCharTelemetryClientJNI.cVirtualDroneCharTelemetry_Ay_set(swigCPtr, this, value);
  }

  public double getAy() {
    return JNIFileMappingDroneCharTelemetryClientJNI.cVirtualDroneCharTelemetry_Ay_get(swigCPtr, this);
  }

  public void setAz(double value) {
    JNIFileMappingDroneCharTelemetryClientJNI.cVirtualDroneCharTelemetry_Az_set(swigCPtr, this, value);
  }

  public double getAz() {
    return JNIFileMappingDroneCharTelemetryClientJNI.cVirtualDroneCharTelemetry_Az_get(swigCPtr, this);
  }

  public void setFrontDistance(double value) {
    JNIFileMappingDroneCharTelemetryClientJNI.cVirtualDroneCharTelemetry_FrontDistance_set(swigCPtr, this, value);
  }

  public double getFrontDistance() {
    return JNIFileMappingDroneCharTelemetryClientJNI.cVirtualDroneCharTelemetry_FrontDistance_get(swigCPtr, this);
  }

  public void setBackDistance(double value) {
    JNIFileMappingDroneCharTelemetryClientJNI.cVirtualDroneCharTelemetry_BackDistance_set(swigCPtr, this, value);
  }

  public double getBackDistance() {
    return JNIFileMappingDroneCharTelemetryClientJNI.cVirtualDroneCharTelemetry_BackDistance_get(swigCPtr, this);
  }

  public void setPressure(double value) {
    JNIFileMappingDroneCharTelemetryClientJNI.cVirtualDroneCharTelemetry_Pressure_set(swigCPtr, this, value);
  }

  public double getPressure() {
    return JNIFileMappingDroneCharTelemetryClientJNI.cVirtualDroneCharTelemetry_Pressure_get(swigCPtr, this);
  }

  public void setDroneCharTelemetryDataPtr(SWIGTYPE_p_unsigned_char value) {
    JNIFileMappingDroneCharTelemetryClientJNI.cVirtualDroneCharTelemetry_DroneCharTelemetryDataPtr_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getDroneCharTelemetryDataPtr() {
    long cPtr = JNIFileMappingDroneCharTelemetryClientJNI.cVirtualDroneCharTelemetry_DroneCharTelemetryDataPtr_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public cVirtualDroneCharTelemetry() {
    this(JNIFileMappingDroneCharTelemetryClientJNI.new_cVirtualDroneCharTelemetry(), true);
  }

}
