/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class JNIFileMappingDroneCharTelemetryClientJNI {
  public final static native void cVirtualDroneCharTelemetry_MutexBlocAccess_set(long jarg1, cVirtualDroneCharTelemetry jarg1_, boolean jarg2);
  public final static native boolean cVirtualDroneCharTelemetry_MutexBlocAccess_get(long jarg1, cVirtualDroneCharTelemetry jarg1_);
  public final static native void cVirtualDroneCharTelemetry_BatteryValue_set(long jarg1, cVirtualDroneCharTelemetry jarg1_, int jarg2);
  public final static native int cVirtualDroneCharTelemetry_BatteryValue_get(long jarg1, cVirtualDroneCharTelemetry jarg1_);
  public final static native void cVirtualDroneCharTelemetry_DriveTime_set(long jarg1, cVirtualDroneCharTelemetry jarg1_, String jarg2);
  public final static native String cVirtualDroneCharTelemetry_DriveTime_get(long jarg1, cVirtualDroneCharTelemetry jarg1_);
  public final static native void cVirtualDroneCharTelemetry_TempC_set(long jarg1, cVirtualDroneCharTelemetry jarg1_, String jarg2);
  public final static native String cVirtualDroneCharTelemetry_TempC_get(long jarg1, cVirtualDroneCharTelemetry jarg1_);
  public final static native void cVirtualDroneCharTelemetry_TempF_set(long jarg1, cVirtualDroneCharTelemetry jarg1_, String jarg2);
  public final static native String cVirtualDroneCharTelemetry_TempF_get(long jarg1, cVirtualDroneCharTelemetry jarg1_);
  public final static native void cVirtualDroneCharTelemetry_Altitude_set(long jarg1, cVirtualDroneCharTelemetry jarg1_, String jarg2);
  public final static native String cVirtualDroneCharTelemetry_Altitude_get(long jarg1, cVirtualDroneCharTelemetry jarg1_);
  public final static native void cVirtualDroneCharTelemetry_Ax_set(long jarg1, cVirtualDroneCharTelemetry jarg1_, double jarg2);
  public final static native double cVirtualDroneCharTelemetry_Ax_get(long jarg1, cVirtualDroneCharTelemetry jarg1_);
  public final static native void cVirtualDroneCharTelemetry_Ay_set(long jarg1, cVirtualDroneCharTelemetry jarg1_, double jarg2);
  public final static native double cVirtualDroneCharTelemetry_Ay_get(long jarg1, cVirtualDroneCharTelemetry jarg1_);
  public final static native void cVirtualDroneCharTelemetry_Az_set(long jarg1, cVirtualDroneCharTelemetry jarg1_, double jarg2);
  public final static native double cVirtualDroneCharTelemetry_Az_get(long jarg1, cVirtualDroneCharTelemetry jarg1_);
  public final static native void cVirtualDroneCharTelemetry_FrontDistance_set(long jarg1, cVirtualDroneCharTelemetry jarg1_, double jarg2);
  public final static native double cVirtualDroneCharTelemetry_FrontDistance_get(long jarg1, cVirtualDroneCharTelemetry jarg1_);
  public final static native void cVirtualDroneCharTelemetry_BackDistance_set(long jarg1, cVirtualDroneCharTelemetry jarg1_, double jarg2);
  public final static native double cVirtualDroneCharTelemetry_BackDistance_get(long jarg1, cVirtualDroneCharTelemetry jarg1_);
  public final static native void cVirtualDroneCharTelemetry_Pressure_set(long jarg1, cVirtualDroneCharTelemetry jarg1_, double jarg2);
  public final static native double cVirtualDroneCharTelemetry_Pressure_get(long jarg1, cVirtualDroneCharTelemetry jarg1_);
  public final static native void cVirtualDroneCharTelemetry_DroneCharTelemetryDataPtr_set(long jarg1, cVirtualDroneCharTelemetry jarg1_, long jarg2);
  public final static native long cVirtualDroneCharTelemetry_DroneCharTelemetryDataPtr_get(long jarg1, cVirtualDroneCharTelemetry jarg1_);
  public final static native long new_cVirtualDroneCharTelemetry();
  public final static native void delete_cVirtualDroneCharTelemetry(long jarg1);
  public final static native long new_cFileMappingDroneCharTelemetryClient(boolean jarg1);
  public final static native void delete_cFileMappingDroneCharTelemetryClient(long jarg1);
  public final static native boolean cFileMappingDroneCharTelemetryClient_OpenClient(long jarg1, cFileMappingDroneCharTelemetryClient jarg1_, String jarg2);
  public final static native void cFileMappingDroneCharTelemetryClient_CloseClient(long jarg1, cFileMappingDroneCharTelemetryClient jarg1_);
  public final static native long cFileMappingDroneCharTelemetryClient_ReadMapFileToVirtualDroneCharTelemetryStruct(long jarg1, cFileMappingDroneCharTelemetryClient jarg1_, long jarg2, cVirtualDroneCharTelemetry jarg2_);
  public final static native boolean cFileMappingDroneCharTelemetryClient_WriteVirtualDroneCharTelemetryStructToMapFile(long jarg1, cFileMappingDroneCharTelemetryClient jarg1_, long jarg2, cVirtualDroneCharTelemetry jarg2_);
  public final static native void cFileMappingDroneCharTelemetryClient_PrintDebug(long jarg1, cFileMappingDroneCharTelemetryClient jarg1_, String jarg2, boolean jarg3);
  public final static native void cFileMappingDroneCharTelemetryClient_PrintStruct(long jarg1, cFileMappingDroneCharTelemetryClient jarg1_, long jarg2, cVirtualDroneCharTelemetry jarg2_);
  public final static native long cFileMappingDroneCharTelemetryClient_getVirtualDroneCharTelemetryPtr(long jarg1, cFileMappingDroneCharTelemetryClient jarg1_);
  public final static native boolean cFileMappingDroneCharTelemetryClient_getDebugMode(long jarg1, cFileMappingDroneCharTelemetryClient jarg1_);
  public final static native int cFileMappingDroneCharTelemetryClient_getVirtualDroneCharTelemetryBatteryValue(long jarg1, cFileMappingDroneCharTelemetryClient jarg1_);
  public final static native String cFileMappingDroneCharTelemetryClient_getVirtualDroneCharTelemetryDriveTime(long jarg1, cFileMappingDroneCharTelemetryClient jarg1_);
  public final static native String cFileMappingDroneCharTelemetryClient_getVirtualDroneCharTelemetryTempC(long jarg1, cFileMappingDroneCharTelemetryClient jarg1_);
  public final static native String cFileMappingDroneCharTelemetryClient_getVirtualDroneCharTelemetryTempF(long jarg1, cFileMappingDroneCharTelemetryClient jarg1_);
  public final static native String cFileMappingDroneCharTelemetryClient_getVirtualDroneCharTelemetryAltitude(long jarg1, cFileMappingDroneCharTelemetryClient jarg1_);
  public final static native double cFileMappingDroneCharTelemetryClient_getVirtualDroneCharTelemetryAx(long jarg1, cFileMappingDroneCharTelemetryClient jarg1_);
  public final static native double cFileMappingDroneCharTelemetryClient_getVirtualDroneCharTelemetryAy(long jarg1, cFileMappingDroneCharTelemetryClient jarg1_);
  public final static native double cFileMappingDroneCharTelemetryClient_getVirtualDroneCharTelemetryAz(long jarg1, cFileMappingDroneCharTelemetryClient jarg1_);
  public final static native double cFileMappingDroneCharTelemetryClient_getVirtualDroneCharTelemetryFrontDistance(long jarg1, cFileMappingDroneCharTelemetryClient jarg1_);
  public final static native double cFileMappingDroneCharTelemetryClient_getVirtualDroneCharTelemetryBackDistance(long jarg1, cFileMappingDroneCharTelemetryClient jarg1_);
  public final static native double cFileMappingDroneCharTelemetryClient_getVirtualDroneCharTelemetryPressure(long jarg1, cFileMappingDroneCharTelemetryClient jarg1_);
  public final static native boolean cFileMappingDroneCharTelemetryClient_getVirtualDroneCharTelemetryMutexBlocAccess(long jarg1, cFileMappingDroneCharTelemetryClient jarg1_);
  public final static native void cFileMappingDroneCharTelemetryClient_setVirtualDroneCharTelemetryPtr(long jarg1, cFileMappingDroneCharTelemetryClient jarg1_, long jarg2, cVirtualDroneCharTelemetry jarg2_);
  public final static native void cFileMappingDroneCharTelemetryClient_setDebugMode(long jarg1, cFileMappingDroneCharTelemetryClient jarg1_, boolean jarg2);
  public final static native void cFileMappingDroneCharTelemetryClient_setVirtualDroneCharTelemetryBatteryValue(long jarg1, cFileMappingDroneCharTelemetryClient jarg1_, int jarg2);
  public final static native void cFileMappingDroneCharTelemetryClient_setVirtualDroneCharTelemetryDriveTime(long jarg1, cFileMappingDroneCharTelemetryClient jarg1_, String jarg2);
  public final static native void cFileMappingDroneCharTelemetryClient_setVirtualDroneCharTelemetryTempC(long jarg1, cFileMappingDroneCharTelemetryClient jarg1_, String jarg2);
  public final static native void cFileMappingDroneCharTelemetryClient_setVirtualDroneCharTelemetryTempF(long jarg1, cFileMappingDroneCharTelemetryClient jarg1_, String jarg2);
  public final static native void cFileMappingDroneCharTelemetryClient_setVirtualDroneCharTelemetryAltitude(long jarg1, cFileMappingDroneCharTelemetryClient jarg1_, String jarg2);
  public final static native void cFileMappingDroneCharTelemetryClient_setVirtualDroneCharTelemetryAx(long jarg1, cFileMappingDroneCharTelemetryClient jarg1_, double jarg2);
  public final static native void cFileMappingDroneCharTelemetryClient_setVirtualDroneCharTelemetryAy(long jarg1, cFileMappingDroneCharTelemetryClient jarg1_, double jarg2);
  public final static native void cFileMappingDroneCharTelemetryClient_setVirtualDroneCharTelemetryAz(long jarg1, cFileMappingDroneCharTelemetryClient jarg1_, double jarg2);
  public final static native void cFileMappingDroneCharTelemetryClient_setVirtualDroneCharTelemetryFrontDistance(long jarg1, cFileMappingDroneCharTelemetryClient jarg1_, double jarg2);
  public final static native void cFileMappingDroneCharTelemetryClient_setVirtualDroneCharTelemetryBackDistance(long jarg1, cFileMappingDroneCharTelemetryClient jarg1_, double jarg2);
  public final static native void cFileMappingDroneCharTelemetryClient_setVirtualDroneCharTelemetryPressure(long jarg1, cFileMappingDroneCharTelemetryClient jarg1_, double jarg2);
  public final static native void cFileMappingDroneCharTelemetryClient_setVirtualDroneCharTelemetryMutexBlocAccess(long jarg1, cFileMappingDroneCharTelemetryClient jarg1_, boolean jarg2);
}
