/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class JNIFileMappingDroneCharTelemetryServeurJNI {
  public final static native void cVirtualDroneCharTelemetry_MutexBlocAccess_set(long jarg1, cVirtualDroneCharTelemetry jarg1_, boolean jarg2);
  public final static native boolean cVirtualDroneCharTelemetry_MutexBlocAccess_get(long jarg1, cVirtualDroneCharTelemetry jarg1_);
  public final static native void cVirtualDroneCharTelemetry_DroneCharTelemetryDataPtr_set(long jarg1, cVirtualDroneCharTelemetry jarg1_, long jarg2);
  public final static native long cVirtualDroneCharTelemetry_DroneCharTelemetryDataPtr_get(long jarg1, cVirtualDroneCharTelemetry jarg1_);
  public final static native void cVirtualDroneCharTelemetry_val_0_set(long jarg1, cVirtualDroneCharTelemetry jarg1_, float jarg2);
  public final static native float cVirtualDroneCharTelemetry_val_0_get(long jarg1, cVirtualDroneCharTelemetry jarg1_);
  public final static native void cVirtualDroneCharTelemetry_val_1_set(long jarg1, cVirtualDroneCharTelemetry jarg1_, float jarg2);
  public final static native float cVirtualDroneCharTelemetry_val_1_get(long jarg1, cVirtualDroneCharTelemetry jarg1_);
  public final static native void cVirtualDroneCharTelemetry_val_2_set(long jarg1, cVirtualDroneCharTelemetry jarg1_, float jarg2);
  public final static native float cVirtualDroneCharTelemetry_val_2_get(long jarg1, cVirtualDroneCharTelemetry jarg1_);
  public final static native void cVirtualDroneCharTelemetry_val_3_set(long jarg1, cVirtualDroneCharTelemetry jarg1_, float jarg2);
  public final static native float cVirtualDroneCharTelemetry_val_3_get(long jarg1, cVirtualDroneCharTelemetry jarg1_);
  public final static native void cVirtualDroneCharTelemetry_val_4_set(long jarg1, cVirtualDroneCharTelemetry jarg1_, float jarg2);
  public final static native float cVirtualDroneCharTelemetry_val_4_get(long jarg1, cVirtualDroneCharTelemetry jarg1_);
  public final static native void cVirtualDroneCharTelemetry_val_5_set(long jarg1, cVirtualDroneCharTelemetry jarg1_, float jarg2);
  public final static native float cVirtualDroneCharTelemetry_val_5_get(long jarg1, cVirtualDroneCharTelemetry jarg1_);
  public final static native void cVirtualDroneCharTelemetry_val_6_set(long jarg1, cVirtualDroneCharTelemetry jarg1_, float jarg2);
  public final static native float cVirtualDroneCharTelemetry_val_6_get(long jarg1, cVirtualDroneCharTelemetry jarg1_);
  public final static native void cVirtualDroneCharTelemetry_val_7_set(long jarg1, cVirtualDroneCharTelemetry jarg1_, float jarg2);
  public final static native float cVirtualDroneCharTelemetry_val_7_get(long jarg1, cVirtualDroneCharTelemetry jarg1_);
  public final static native void cVirtualDroneCharTelemetry_val_8_set(long jarg1, cVirtualDroneCharTelemetry jarg1_, float jarg2);
  public final static native float cVirtualDroneCharTelemetry_val_8_get(long jarg1, cVirtualDroneCharTelemetry jarg1_);
  public final static native void cVirtualDroneCharTelemetry_val_9_set(long jarg1, cVirtualDroneCharTelemetry jarg1_, float jarg2);
  public final static native float cVirtualDroneCharTelemetry_val_9_get(long jarg1, cVirtualDroneCharTelemetry jarg1_);
  public final static native void cVirtualDroneCharTelemetry_val_10_set(long jarg1, cVirtualDroneCharTelemetry jarg1_, float jarg2);
  public final static native float cVirtualDroneCharTelemetry_val_10_get(long jarg1, cVirtualDroneCharTelemetry jarg1_);
  public final static native void cVirtualDroneCharTelemetry_val_11_set(long jarg1, cVirtualDroneCharTelemetry jarg1_, float jarg2);
  public final static native float cVirtualDroneCharTelemetry_val_11_get(long jarg1, cVirtualDroneCharTelemetry jarg1_);
  public final static native void cVirtualDroneCharTelemetry_val_12_set(long jarg1, cVirtualDroneCharTelemetry jarg1_, float jarg2);
  public final static native float cVirtualDroneCharTelemetry_val_12_get(long jarg1, cVirtualDroneCharTelemetry jarg1_);
  public final static native void cVirtualDroneCharTelemetry_val_13_set(long jarg1, cVirtualDroneCharTelemetry jarg1_, float jarg2);
  public final static native float cVirtualDroneCharTelemetry_val_13_get(long jarg1, cVirtualDroneCharTelemetry jarg1_);
  public final static native void cVirtualDroneCharTelemetry_val_14_set(long jarg1, cVirtualDroneCharTelemetry jarg1_, float jarg2);
  public final static native float cVirtualDroneCharTelemetry_val_14_get(long jarg1, cVirtualDroneCharTelemetry jarg1_);
  public final static native void cVirtualDroneCharTelemetry_val_15_set(long jarg1, cVirtualDroneCharTelemetry jarg1_, float jarg2);
  public final static native float cVirtualDroneCharTelemetry_val_15_get(long jarg1, cVirtualDroneCharTelemetry jarg1_);
  public final static native void cVirtualDroneCharTelemetry_val_16_set(long jarg1, cVirtualDroneCharTelemetry jarg1_, float jarg2);
  public final static native float cVirtualDroneCharTelemetry_val_16_get(long jarg1, cVirtualDroneCharTelemetry jarg1_);
  public final static native void cVirtualDroneCharTelemetry_val_17_set(long jarg1, cVirtualDroneCharTelemetry jarg1_, float jarg2);
  public final static native float cVirtualDroneCharTelemetry_val_17_get(long jarg1, cVirtualDroneCharTelemetry jarg1_);
  public final static native void cVirtualDroneCharTelemetry_val_18_set(long jarg1, cVirtualDroneCharTelemetry jarg1_, float jarg2);
  public final static native float cVirtualDroneCharTelemetry_val_18_get(long jarg1, cVirtualDroneCharTelemetry jarg1_);
  public final static native void cVirtualDroneCharTelemetry_val_19_set(long jarg1, cVirtualDroneCharTelemetry jarg1_, float jarg2);
  public final static native float cVirtualDroneCharTelemetry_val_19_get(long jarg1, cVirtualDroneCharTelemetry jarg1_);
  public final static native long new_cVirtualDroneCharTelemetry();
  public final static native void delete_cVirtualDroneCharTelemetry(long jarg1);
  public final static native long new_cFileMappingDroneCharTelemetryServeur(boolean jarg1);
  public final static native void delete_cFileMappingDroneCharTelemetryServeur(long jarg1);
  public final static native boolean cFileMappingDroneCharTelemetryServeur_OpenServer(long jarg1, cFileMappingDroneCharTelemetryServeur jarg1_, String jarg2);
  public final static native void cFileMappingDroneCharTelemetryServeur_CloseServer(long jarg1, cFileMappingDroneCharTelemetryServeur jarg1_);
  public final static native long cFileMappingDroneCharTelemetryServeur_ReadMapFileToVirtualDroneCharTelemetryStruct(long jarg1, cFileMappingDroneCharTelemetryServeur jarg1_, long jarg2, cVirtualDroneCharTelemetry jarg2_);
  public final static native boolean cFileMappingDroneCharTelemetryServeur_WriteVirtualDroneCharTelemetryStructToMapFile(long jarg1, cFileMappingDroneCharTelemetryServeur jarg1_, long jarg2, cVirtualDroneCharTelemetry jarg2_);
  public final static native void cFileMappingDroneCharTelemetryServeur_PrintDebug(long jarg1, cFileMappingDroneCharTelemetryServeur jarg1_, String jarg2, boolean jarg3);
  public final static native void cFileMappingDroneCharTelemetryServeur_PrintStruct(long jarg1, cFileMappingDroneCharTelemetryServeur jarg1_, long jarg2, cVirtualDroneCharTelemetry jarg2_);
  public final static native boolean cFileMappingDroneCharTelemetryServeur_getDebugMode(long jarg1, cFileMappingDroneCharTelemetryServeur jarg1_);
  public final static native long cFileMappingDroneCharTelemetryServeur_getVirtualDroneCharTelemetryPtr(long jarg1, cFileMappingDroneCharTelemetryServeur jarg1_);
  public final static native boolean cFileMappingDroneCharTelemetryServeur_getVirtualDroneCharTelemetryMutexBlocAccess(long jarg1, cFileMappingDroneCharTelemetryServeur jarg1_);
  public final static native double cFileMappingDroneCharTelemetryServeur_get_val_0(long jarg1, cFileMappingDroneCharTelemetryServeur jarg1_);
  public final static native double cFileMappingDroneCharTelemetryServeur_get_val_1(long jarg1, cFileMappingDroneCharTelemetryServeur jarg1_);
  public final static native double cFileMappingDroneCharTelemetryServeur_get_val_2(long jarg1, cFileMappingDroneCharTelemetryServeur jarg1_);
  public final static native double cFileMappingDroneCharTelemetryServeur_get_val_3(long jarg1, cFileMappingDroneCharTelemetryServeur jarg1_);
  public final static native double cFileMappingDroneCharTelemetryServeur_get_val_4(long jarg1, cFileMappingDroneCharTelemetryServeur jarg1_);
  public final static native double cFileMappingDroneCharTelemetryServeur_get_val_5(long jarg1, cFileMappingDroneCharTelemetryServeur jarg1_);
  public final static native double cFileMappingDroneCharTelemetryServeur_get_val_6(long jarg1, cFileMappingDroneCharTelemetryServeur jarg1_);
  public final static native double cFileMappingDroneCharTelemetryServeur_get_val_7(long jarg1, cFileMappingDroneCharTelemetryServeur jarg1_);
  public final static native double cFileMappingDroneCharTelemetryServeur_get_val_8(long jarg1, cFileMappingDroneCharTelemetryServeur jarg1_);
  public final static native double cFileMappingDroneCharTelemetryServeur_get_val_9(long jarg1, cFileMappingDroneCharTelemetryServeur jarg1_);
  public final static native double cFileMappingDroneCharTelemetryServeur_get_val_10(long jarg1, cFileMappingDroneCharTelemetryServeur jarg1_);
  public final static native double cFileMappingDroneCharTelemetryServeur_get_val_11(long jarg1, cFileMappingDroneCharTelemetryServeur jarg1_);
  public final static native double cFileMappingDroneCharTelemetryServeur_get_val_12(long jarg1, cFileMappingDroneCharTelemetryServeur jarg1_);
  public final static native double cFileMappingDroneCharTelemetryServeur_get_val_13(long jarg1, cFileMappingDroneCharTelemetryServeur jarg1_);
  public final static native double cFileMappingDroneCharTelemetryServeur_get_val_14(long jarg1, cFileMappingDroneCharTelemetryServeur jarg1_);
  public final static native double cFileMappingDroneCharTelemetryServeur_get_val_15(long jarg1, cFileMappingDroneCharTelemetryServeur jarg1_);
  public final static native double cFileMappingDroneCharTelemetryServeur_get_val_16(long jarg1, cFileMappingDroneCharTelemetryServeur jarg1_);
  public final static native double cFileMappingDroneCharTelemetryServeur_get_val_17(long jarg1, cFileMappingDroneCharTelemetryServeur jarg1_);
  public final static native double cFileMappingDroneCharTelemetryServeur_get_val_18(long jarg1, cFileMappingDroneCharTelemetryServeur jarg1_);
  public final static native double cFileMappingDroneCharTelemetryServeur_get_val_19(long jarg1, cFileMappingDroneCharTelemetryServeur jarg1_);
  public final static native void cFileMappingDroneCharTelemetryServeur_setDebugMode(long jarg1, cFileMappingDroneCharTelemetryServeur jarg1_, boolean jarg2);
  public final static native void cFileMappingDroneCharTelemetryServeur_setVirtualDroneCharTelemetryPtr(long jarg1, cFileMappingDroneCharTelemetryServeur jarg1_, long jarg2, cVirtualDroneCharTelemetry jarg2_);
  public final static native void cFileMappingDroneCharTelemetryServeur_setVirtualDroneCharTelemetryMutexBlocAccess(long jarg1, cFileMappingDroneCharTelemetryServeur jarg1_, boolean jarg2);
  public final static native void cFileMappingDroneCharTelemetryServeur_set_val_0(long jarg1, cFileMappingDroneCharTelemetryServeur jarg1_, double jarg2);
  public final static native void cFileMappingDroneCharTelemetryServeur_set_val_1(long jarg1, cFileMappingDroneCharTelemetryServeur jarg1_, double jarg2);
  public final static native void cFileMappingDroneCharTelemetryServeur_set_val_2(long jarg1, cFileMappingDroneCharTelemetryServeur jarg1_, double jarg2);
  public final static native void cFileMappingDroneCharTelemetryServeur_set_val_3(long jarg1, cFileMappingDroneCharTelemetryServeur jarg1_, double jarg2);
  public final static native void cFileMappingDroneCharTelemetryServeur_set_val_4(long jarg1, cFileMappingDroneCharTelemetryServeur jarg1_, double jarg2);
  public final static native void cFileMappingDroneCharTelemetryServeur_set_val_5(long jarg1, cFileMappingDroneCharTelemetryServeur jarg1_, double jarg2);
  public final static native void cFileMappingDroneCharTelemetryServeur_set_val_6(long jarg1, cFileMappingDroneCharTelemetryServeur jarg1_, double jarg2);
  public final static native void cFileMappingDroneCharTelemetryServeur_set_val_7(long jarg1, cFileMappingDroneCharTelemetryServeur jarg1_, double jarg2);
  public final static native void cFileMappingDroneCharTelemetryServeur_set_val_8(long jarg1, cFileMappingDroneCharTelemetryServeur jarg1_, double jarg2);
  public final static native void cFileMappingDroneCharTelemetryServeur_set_val_9(long jarg1, cFileMappingDroneCharTelemetryServeur jarg1_, double jarg2);
  public final static native void cFileMappingDroneCharTelemetryServeur_set_val_10(long jarg1, cFileMappingDroneCharTelemetryServeur jarg1_, double jarg2);
  public final static native void cFileMappingDroneCharTelemetryServeur_set_val_11(long jarg1, cFileMappingDroneCharTelemetryServeur jarg1_, double jarg2);
  public final static native void cFileMappingDroneCharTelemetryServeur_set_val_12(long jarg1, cFileMappingDroneCharTelemetryServeur jarg1_, double jarg2);
  public final static native void cFileMappingDroneCharTelemetryServeur_set_val_13(long jarg1, cFileMappingDroneCharTelemetryServeur jarg1_, double jarg2);
  public final static native void cFileMappingDroneCharTelemetryServeur_set_val_14(long jarg1, cFileMappingDroneCharTelemetryServeur jarg1_, double jarg2);
  public final static native void cFileMappingDroneCharTelemetryServeur_set_val_15(long jarg1, cFileMappingDroneCharTelemetryServeur jarg1_, double jarg2);
  public final static native void cFileMappingDroneCharTelemetryServeur_set_val_16(long jarg1, cFileMappingDroneCharTelemetryServeur jarg1_, double jarg2);
  public final static native void cFileMappingDroneCharTelemetryServeur_set_val_17(long jarg1, cFileMappingDroneCharTelemetryServeur jarg1_, double jarg2);
  public final static native void cFileMappingDroneCharTelemetryServeur_set_val_18(long jarg1, cFileMappingDroneCharTelemetryServeur jarg1_, double jarg2);
  public final static native void cFileMappingDroneCharTelemetryServeur_set_val_19(long jarg1, cFileMappingDroneCharTelemetryServeur jarg1_, double jarg2);
}
