/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class JNIVirtualDroneCharTelemetryJNI {
  public final static native void cVirtualDroneCharTelemetry_MutexBlocAccess_set(long jarg1, cVirtualDroneCharTelemetry jarg1_, boolean jarg2);
  public final static native boolean cVirtualDroneCharTelemetry_MutexBlocAccess_get(long jarg1, cVirtualDroneCharTelemetry jarg1_);
  public final static native void cVirtualDroneCharTelemetry_DroneCharTelemetryDataPtr_set(long jarg1, cVirtualDroneCharTelemetry jarg1_, long jarg2);
  public final static native long cVirtualDroneCharTelemetry_DroneCharTelemetryDataPtr_get(long jarg1, cVirtualDroneCharTelemetry jarg1_);
  public final static native void cVirtualDroneCharTelemetry_val_0_set(long jarg1, cVirtualDroneCharTelemetry jarg1_, float jarg2);
  public final static native float cVirtualDroneCharTelemetry_val_0_get(long jarg1, cVirtualDroneCharTelemetry jarg1_);
  public final static native void cVirtualDroneCharTelemetry_val_1_set(long jarg1, cVirtualDroneCharTelemetry jarg1_, float jarg2);
  public final static native float cVirtualDroneCharTelemetry_val_1_get(long jarg1, cVirtualDroneCharTelemetry jarg1_);
  public final static native void cVirtualDroneCharTelemetry_val_2_set(long jarg1, cVirtualDroneCharTelemetry jarg1_, float jarg2);
  public final static native float cVirtualDroneCharTelemetry_val_2_get(long jarg1, cVirtualDroneCharTelemetry jarg1_);
  public final static native void cVirtualDroneCharTelemetry_val_3_set(long jarg1, cVirtualDroneCharTelemetry jarg1_, float jarg2);
  public final static native float cVirtualDroneCharTelemetry_val_3_get(long jarg1, cVirtualDroneCharTelemetry jarg1_);
  public final static native void cVirtualDroneCharTelemetry_val_4_set(long jarg1, cVirtualDroneCharTelemetry jarg1_, float jarg2);
  public final static native float cVirtualDroneCharTelemetry_val_4_get(long jarg1, cVirtualDroneCharTelemetry jarg1_);
  public final static native void cVirtualDroneCharTelemetry_val_5_set(long jarg1, cVirtualDroneCharTelemetry jarg1_, float jarg2);
  public final static native float cVirtualDroneCharTelemetry_val_5_get(long jarg1, cVirtualDroneCharTelemetry jarg1_);
  public final static native void cVirtualDroneCharTelemetry_val_6_set(long jarg1, cVirtualDroneCharTelemetry jarg1_, float jarg2);
  public final static native float cVirtualDroneCharTelemetry_val_6_get(long jarg1, cVirtualDroneCharTelemetry jarg1_);
  public final static native void cVirtualDroneCharTelemetry_val_7_set(long jarg1, cVirtualDroneCharTelemetry jarg1_, float jarg2);
  public final static native float cVirtualDroneCharTelemetry_val_7_get(long jarg1, cVirtualDroneCharTelemetry jarg1_);
  public final static native void cVirtualDroneCharTelemetry_val_8_set(long jarg1, cVirtualDroneCharTelemetry jarg1_, float jarg2);
  public final static native float cVirtualDroneCharTelemetry_val_8_get(long jarg1, cVirtualDroneCharTelemetry jarg1_);
  public final static native void cVirtualDroneCharTelemetry_val_9_set(long jarg1, cVirtualDroneCharTelemetry jarg1_, float jarg2);
  public final static native float cVirtualDroneCharTelemetry_val_9_get(long jarg1, cVirtualDroneCharTelemetry jarg1_);
  public final static native void cVirtualDroneCharTelemetry_val_10_set(long jarg1, cVirtualDroneCharTelemetry jarg1_, float jarg2);
  public final static native float cVirtualDroneCharTelemetry_val_10_get(long jarg1, cVirtualDroneCharTelemetry jarg1_);
  public final static native void cVirtualDroneCharTelemetry_val_11_set(long jarg1, cVirtualDroneCharTelemetry jarg1_, float jarg2);
  public final static native float cVirtualDroneCharTelemetry_val_11_get(long jarg1, cVirtualDroneCharTelemetry jarg1_);
  public final static native void cVirtualDroneCharTelemetry_val_12_set(long jarg1, cVirtualDroneCharTelemetry jarg1_, float jarg2);
  public final static native float cVirtualDroneCharTelemetry_val_12_get(long jarg1, cVirtualDroneCharTelemetry jarg1_);
  public final static native void cVirtualDroneCharTelemetry_val_13_set(long jarg1, cVirtualDroneCharTelemetry jarg1_, float jarg2);
  public final static native float cVirtualDroneCharTelemetry_val_13_get(long jarg1, cVirtualDroneCharTelemetry jarg1_);
  public final static native void cVirtualDroneCharTelemetry_val_14_set(long jarg1, cVirtualDroneCharTelemetry jarg1_, float jarg2);
  public final static native float cVirtualDroneCharTelemetry_val_14_get(long jarg1, cVirtualDroneCharTelemetry jarg1_);
  public final static native void cVirtualDroneCharTelemetry_val_15_set(long jarg1, cVirtualDroneCharTelemetry jarg1_, float jarg2);
  public final static native float cVirtualDroneCharTelemetry_val_15_get(long jarg1, cVirtualDroneCharTelemetry jarg1_);
  public final static native void cVirtualDroneCharTelemetry_val_16_set(long jarg1, cVirtualDroneCharTelemetry jarg1_, float jarg2);
  public final static native float cVirtualDroneCharTelemetry_val_16_get(long jarg1, cVirtualDroneCharTelemetry jarg1_);
  public final static native void cVirtualDroneCharTelemetry_val_17_set(long jarg1, cVirtualDroneCharTelemetry jarg1_, float jarg2);
  public final static native float cVirtualDroneCharTelemetry_val_17_get(long jarg1, cVirtualDroneCharTelemetry jarg1_);
  public final static native void cVirtualDroneCharTelemetry_val_18_set(long jarg1, cVirtualDroneCharTelemetry jarg1_, float jarg2);
  public final static native float cVirtualDroneCharTelemetry_val_18_get(long jarg1, cVirtualDroneCharTelemetry jarg1_);
  public final static native void cVirtualDroneCharTelemetry_val_19_set(long jarg1, cVirtualDroneCharTelemetry jarg1_, float jarg2);
  public final static native float cVirtualDroneCharTelemetry_val_19_get(long jarg1, cVirtualDroneCharTelemetry jarg1_);
  public final static native long new_cVirtualDroneCharTelemetry();
  public final static native void delete_cVirtualDroneCharTelemetry(long jarg1);
}
