/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class JNIVirtualDroneCharTelemetryJNI {
  public final static native void cVirtualDroneCharTelemetry_MutexBlocAccess_set(long jarg1, cVirtualDroneCharTelemetry jarg1_, boolean jarg2);
  public final static native boolean cVirtualDroneCharTelemetry_MutexBlocAccess_get(long jarg1, cVirtualDroneCharTelemetry jarg1_);
  public final static native void cVirtualDroneCharTelemetry_BatteryValue_set(long jarg1, cVirtualDroneCharTelemetry jarg1_, int jarg2);
  public final static native int cVirtualDroneCharTelemetry_BatteryValue_get(long jarg1, cVirtualDroneCharTelemetry jarg1_);
  public final static native void cVirtualDroneCharTelemetry_DriveTime_set(long jarg1, cVirtualDroneCharTelemetry jarg1_, String jarg2);
  public final static native String cVirtualDroneCharTelemetry_DriveTime_get(long jarg1, cVirtualDroneCharTelemetry jarg1_);
  public final static native void cVirtualDroneCharTelemetry_TempC_set(long jarg1, cVirtualDroneCharTelemetry jarg1_, String jarg2);
  public final static native String cVirtualDroneCharTelemetry_TempC_get(long jarg1, cVirtualDroneCharTelemetry jarg1_);
  public final static native void cVirtualDroneCharTelemetry_TempF_set(long jarg1, cVirtualDroneCharTelemetry jarg1_, String jarg2);
  public final static native String cVirtualDroneCharTelemetry_TempF_get(long jarg1, cVirtualDroneCharTelemetry jarg1_);
  public final static native void cVirtualDroneCharTelemetry_Altitude_set(long jarg1, cVirtualDroneCharTelemetry jarg1_, String jarg2);
  public final static native String cVirtualDroneCharTelemetry_Altitude_get(long jarg1, cVirtualDroneCharTelemetry jarg1_);
  public final static native void cVirtualDroneCharTelemetry_Ax_set(long jarg1, cVirtualDroneCharTelemetry jarg1_, double jarg2);
  public final static native double cVirtualDroneCharTelemetry_Ax_get(long jarg1, cVirtualDroneCharTelemetry jarg1_);
  public final static native void cVirtualDroneCharTelemetry_Ay_set(long jarg1, cVirtualDroneCharTelemetry jarg1_, double jarg2);
  public final static native double cVirtualDroneCharTelemetry_Ay_get(long jarg1, cVirtualDroneCharTelemetry jarg1_);
  public final static native void cVirtualDroneCharTelemetry_Az_set(long jarg1, cVirtualDroneCharTelemetry jarg1_, double jarg2);
  public final static native double cVirtualDroneCharTelemetry_Az_get(long jarg1, cVirtualDroneCharTelemetry jarg1_);
  public final static native void cVirtualDroneCharTelemetry_FrontDistance_set(long jarg1, cVirtualDroneCharTelemetry jarg1_, double jarg2);
  public final static native double cVirtualDroneCharTelemetry_FrontDistance_get(long jarg1, cVirtualDroneCharTelemetry jarg1_);
  public final static native void cVirtualDroneCharTelemetry_BackDistance_set(long jarg1, cVirtualDroneCharTelemetry jarg1_, double jarg2);
  public final static native double cVirtualDroneCharTelemetry_BackDistance_get(long jarg1, cVirtualDroneCharTelemetry jarg1_);
  public final static native void cVirtualDroneCharTelemetry_Pressure_set(long jarg1, cVirtualDroneCharTelemetry jarg1_, double jarg2);
  public final static native double cVirtualDroneCharTelemetry_Pressure_get(long jarg1, cVirtualDroneCharTelemetry jarg1_);
  public final static native void cVirtualDroneCharTelemetry_DroneCharTelemetryDataPtr_set(long jarg1, cVirtualDroneCharTelemetry jarg1_, long jarg2);
  public final static native long cVirtualDroneCharTelemetry_DroneCharTelemetryDataPtr_get(long jarg1, cVirtualDroneCharTelemetry jarg1_);
  public final static native long new_cVirtualDroneCharTelemetry();
  public final static native void delete_cVirtualDroneCharTelemetry(long jarg1);
}
