package filemap;
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public interface JNIFileMappingPictureClientConstants {
  public final static int STRUCT_DATAPICTURE_BUFFER_SIZE = JNIFileMappingPictureClientJNI.STRUCT_DATAPICTURE_BUFFER_SIZE_get();
}
